### ISSUE TITLE
Cannot ls folders with unusual names

### ISSUE THREAD

**Issue by lukasz-wronski** [sparkida/ftpimp#11]
When I'm trying to LS folder that contains non-alphanumeric named folders in it I'm getting error.
 
I'm trying to ls content of folder: `/public_html/x/Angular-Hero-Sample-master/node_modules/bower/node_modules/inquirer/node_modules/cli-color/node_modules/memoizee/node_modules/es6-weak-map/node_modules/es6-iterator`

This folder contains another folder with name: `#`

I am getting following exception:

```
TypeError: Cannot read property '1' of null
    at Object.StatObject (c:\Projects\vs-code-ftpsync\ftp-sync\node_modules\ftpimp\index.js:1494:28)
    at Function.StatObject.create (c:\Projects\vs-code-ftpsync\ftp-sync\node_modules\ftpimp\index.js:1620:12)
    at c:\Projects\vs-code-ftpsync\ftp-sync\node_modules\ftpimp\index.js:1675:21
    at null.callback (c:\Projects\vs-code-ftpsync\ftp-sync\node_modules\ftpimp\index.js:636:14)
    at ExeQueue._closePipe (c:\Projects\vs-code-ftpsync\ftp-sync\node_modules\ftpimp\index.js:384:11)
    at Socket.that.(anonymous function) (c:\Projects\vs-code-ftpsync\ftp-sync\node_modules\ftpimp\index.js:308:32)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:441:9)
```

Also the same with another folder name: `中文`

**Comment by sparkida** [comment]
Basically, the ls hook wasn't trying to match those characters. I changed the regex to match anything and added a test to make sure we don't lose this functionality in the future. Let me know if the issue persists. Cheers!

**Comment by sparkida** [comment]
be sure to pull new version 2.2.33

**Comment by lukasz-wronski** [comment]
Yep, now it works fine. Thanks.
