### ISSUE TITLE
Something wrong with Passive mode

### ISSUE THREAD

**Issue by hungbya** [sparkida/ftpimp#31]
Below is my very simple code

```javascript
const ftp = Ftp.create(ftpConfig, true);
ftp.once('ready', ()=>{
   ftp.ls('.', (err, res)=> {
       debugger
   })
});
```
But it will never reach the debugger, and the logs in debugging mode after connected

```
...
Event> endproc
Queue> Loading queue
--queue empty--
current dir: in
ftp.Run:  false PASV
Queue> Registering callback...
Queue> processing: false; size: 0
Queue> Loading queue
Queue> Loaded...running
Run> running callbackConstruct PASV
PASV false false
Run> command sent: PASV
....................

>>>
501 syntax error
>>>

501
------------------
CODE  -> 501
DATA -> syntax error
------------------
handle.data.waiting: true 501
handle.data.waiting:: 501 syntax error
calling : _responseHandler > PASV { '0': 501, '1': 'syntax error' }
Response handler: 501 syntax error
calling : _endStopwatch > PASV {}
handling error response code...
ExeQueue {
  command: 'PASV',
  method: 'PASV',
  pipeData: [],
  pipeDataSize: 0,
  holdQueue: false,
  callback: [Function],
  runLevel: false,
  ended: 1492422151184,
  ping: 70,
  end: [Function],
  endStopwatch: [Function],
  checkProc: [Function],
  closeTransfer: [Function],
  closePipe: [Function],
  responseHandler: [Function],
  receiveData: [Function],
  started: 1492422151114 }
killing pipe
data not bound:  TypeError: Cannot read property 'removeListener' of null
    at ExeQueue._responseHandler (/mnt/app/sms/node_modules/ftpimp/index.js:408:21)
    at FTP.that.(anonymous function) (/mnt/app/sms/node_modules/ftpimp/index.js:308:32)
    at Object.onceWrapper (events.js:291:19)
    at emitTwo (events.js:106:13)
    at FTP.emit (events.js:192:7)
    at end (/mnt/app/sms/node_modules/ftpimp/index.js:824:25)
    at run (/mnt/app/sms/node_modules/ftpimp/index.js:847:17)
    at Socket.handle.data (/mnt/app/sms/node_modules/ftpimp/index.js:874:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:189:7)
Queue.builder:: LIST . > setting 
undefined undefined
Queue> Registering callback...
Queue> processing: true; size: 0
calling : _checkProc > PASV {}
check process for end:  ExeQueue {
  command: 'PASV',
  method: 'PASV',
  pipeData: [],
  pipeDataSize: 0,
  holdQueue: false,
  callback: [Function],
  runLevel: false,
  ended: 1492422151184,
  ping: 70,
  end: [Function],
  endStopwatch: [Function],
  checkProc: [Function],
  closeTransfer: [Function],
  closePipe: [Function],
  responseHandler: [Function],
  receiveData: [Function],
  started: 1492422151114 }
ExeQueue> Ending process: PASV
Event> endproc
Queue> Loading queue
Queue> Loaded...running
type set
holdQ:  true
ftp.Run:  true PASV
Queue> Registering callback...
Queue> processing: true; size: 0
Run> running callbackConstruct PASV
PASV 1 true
current dir: 
Run> command sent: PASV
....................

>>>
503 need USER first
>>>

503
------------------
CODE  -> 503
DATA -> need USER first
------------------
handle.data.waiting: true 503
handle.data.waiting:: 503 need USER first
calling : _responseHandler > PASV { '0': 503, '1': 'need USER first' }
Response handler: 503 need USER first
calling : _endStopwatch > PASV {}
handling error response code...
ExeQueue {
  command: 'PASV',
  method: 'PASV',
  pipeData: [],
  pipeDataSize: 0,
  holdQueue: true,
  callback: [Function: dataHandler],
  runLevel: 1,
  ended: 1492422151208,
  ping: 16,
  end: [Function],
  endStopwatch: [Function],
  checkProc: [Function],
  closeTransfer: [Function],
  closePipe: [Function],
  responseHandler: [Function],
  receiveData: [Function],
  started: 1492422151192 }
killing pipe
data not bound:  TypeError: Cannot read property 'removeListener' of null
    at ExeQueue._responseHandler (/mnt/app/sms/node_modules/ftpimp/index.js:408:21)
    at FTP.that.(anonymous function) (/mnt/app/sms/node_modules/ftpimp/index.js:308:32)
    at Object.onceWrapper (events.js:291:19)
    at emitTwo (events.js:106:13)
    at FTP.emit (events.js:192:7)
    at end (/mnt/app/sms/node_modules/ftpimp/index.js:824:25)
    at run (/mnt/app/sms/node_modules/ftpimp/index.js:847:17)
    at Socket.handle.data (/mnt/app/sms/node_modules/ftpimp/index.js:874:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:189:7)
error opening data port with PASV
Error: need USER first
    at ExeQueue._responseHandler (/mnt/app/sms/node_modules/ftpimp/index.js:415:27)
    at FTP.that.(anonymous function) (/mnt/app/sms/node_modules/ftpimp/index.js:308:32)
    at Object.onceWrapper (events.js:291:19)
    at emitTwo (events.js:106:13)
    at FTP.emit (events.js:192:7)
    at end (/mnt/app/sms/node_modules/ftpimp/index.js:824:25)
    at run (/mnt/app/sms/node_modules/ftpimp/index.js:847:17)
    at Socket.handle.data (/mnt/app/sms/node_modules/ftpimp/index.js:874:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:189:7)
calling : _checkProc > PASV {}
check process for end:  ExeQueue {
  command: 'PASV',
  method: 'PASV',
  pipeData: [],
  pipeDataSize: 0,
  holdQueue: true,
  callback: [Function: dataHandler],
  runLevel: 1,
  ended: 1492422151208,
  ping: 16,
  end: [Function],
  endStopwatch: [Function],
  checkProc: [Function],
  closeTransfer: [Function],
  closePipe: [Function],
  responseHandler: [Function],
  receiveData: [Function],
  started: 1492422151192 }
ExeQueue> Ending process, holding queue: PASV
....................

>>>
501 syntax error
>>>

501
------------------
CODE  -> 501
DATA -> syntax error
------------------
handle.data.waiting: false 501
....................

>>>
227 Entering Passive Mode (10,54,9,54,181,127)
227 Entering Passive Mode (10,54,9,54,185,109)
>>>

227
------------------
CODE  -> 227
DATA -> Entering Passive Mode (10,54,9,54,181,127) Entering Passive Mode (10,54,9,54,185,109)
------------------
>executing command: startPassive
passive settings updated
handle.data.waiting: true 227
handle.data.waiting:: 227 Entering Passive Mode (10,54,9,54,181,127) Entering Passive Mode (10,54,9,54,185,109)
```

**Comment by sparkida** [comment]
I'll take a look shortly

**Comment by sparkida** [comment]
Can you paste the debug log starting from beginning (delete any server ip or username, but include server messages) trying to reproduce the issue but unable to.

**Comment by hungbya** [comment]
Here is the debug log:
```
connected: ***.***.***.***:21
socket connected!
....................

>>>
220-WELCOME TO THE ***FTP SERVER
>>>

220
------------------
CODE  -> 220
DATA -> -WELCOME TO THE ***FTP SERVER
------------------
>executing command: login
>Authenticating...
ftp.Run:  false USER USERNAME
Queue> Registering callback...
Queue> processing: false; size: 0
Queue> Loading queue
Queue> Loaded...running
Run> running callbackConstruct USER USERNAME
USER USERNAME false false
handle.data.waiting: true 220
handle.data.waiting:: 220 -WELCOME TO THE ***FTP SERVER
Run> command sent: USER USERNAME
....................

>>>
220 ready
>>>

220
------------------
CODE  -> 220
DATA -> ready
------------------
>executing command: login
>Authenticating...
ftp.Run:  false USER USERNAME
Queue> Registering callback...
Queue> processing: true; size: 0
handle.data.waiting: true 220
handle.data.waiting:: 220 ready
calling : _responseHandler > USER USERNAME { '0': 220, '1': 'ready' }
Response handler: 220 ready
calling : _endStopwatch > USER USERNAME {}
ready
user sent
ftp.Run:  false PASS PASSWORD
Queue> Registering callback...
Queue> processing: true; size: 1
calling : _checkProc > USER USERNAME {}
check process for end:  ExeQueue {
  command: 'USER USERNAME',
  method: 'USER',
  pipeData: [],
  pipeDataSize: 0,
  holdQueue: false,
  callback: [Function],
  runLevel: false,
  ended: 1492574329985,
  ping: 28,
  end: [Function],
  endStopwatch: [Function],
  checkProc: [Function],
  closeTransfer: [Function],
  closePipe: [Function],
  responseHandler: [Function],
  receiveData: [Function],
  started: 1492574329957 }
ExeQueue> Ending process: USER USERNAME
Event> endproc
Queue> Loading queue
Queue> Loaded...running
Run> running callbackConstruct USER USERNAME
USER USERNAME false false
Run> command sent: USER USERNAME
....................

>>>
331 password required
>>>

331
------------------
CODE  -> 331
DATA -> password required
------------------
handle.data.waiting: true 331
handle.data.waiting:: 331 password required
calling : _responseHandler > USER USERNAME { '0': 331, '1': 'password required' }
Response handler: 331 password required
calling : _endStopwatch > USER USERNAME {}
password required
user sent
ftp.Run:  false PASS PASSWORD
Queue> Registering callback...
Queue> processing: true; size: 1
calling : _checkProc > USER USERNAME {}
check process for end:  ExeQueue {
  command: 'USER USERNAME',
  method: 'USER',
  pipeData: [],
  pipeDataSize: 0,
  holdQueue: false,
  callback: [Function],
  runLevel: false,
  ended: 1492574330050,
  ping: 61,
  end: [Function],
  endStopwatch: [Function],
  checkProc: [Function],
  closeTransfer: [Function],
  closePipe: [Function],
  responseHandler: [Function],
  receiveData: [Function],
  started: 1492574329989 }
ExeQueue> Ending process: USER USERNAME
Event> endproc
Queue> Loading queue
Queue> Loaded...running
Run> running callbackConstruct PASS PASSWORD
PASS PASSWORD false false
Run> command sent: PASS PASSWORD
....................

>>>
331 password required
>>>

331
------------------
CODE  -> 331
DATA -> password required
------------------
handle.data.waiting: true 331
handle.data.waiting:: 331 password required
calling : _responseHandler > PASS PASSWORD { '0': 331, '1': 'password required' }
Response handler: 331 password required
calling : _endStopwatch > PASS PASSWORD {}
password sent
calling : _checkProc > PASS PASSWORD {}
check process for end:  ExeQueue {
  command: 'PASS PASSWORD',
  method: 'PASS',
  pipeData: [],
  pipeDataSize: 0,
  holdQueue: false,
  callback: [Function],
  runLevel: false,
  ended: 1492574330079,
  ping: 28,
  end: [Function],
  endStopwatch: [Function],
  checkProc: [Function],
  closeTransfer: [Function],
  closePipe: [Function],
  responseHandler: [Function],
  receiveData: [Function],
  started: 1492574330051 }
ExeQueue> Ending process: PASS PASSWORD
Event> endproc
Queue> Loading queue
Queue> Loaded...running
Run> running callbackConstruct PASS PASSWORD
PASS PASSWORD false false
Run> command sent: PASS PASSWORD
....................

>>>
230 logged in
>>>

230
------------------
CODE  -> 230
DATA -> logged in
------------------
>executing command: ready
handle.data.waiting: true 230
handle.data.waiting:: 230 logged in
calling : _responseHandler > PASS PASSWORD { '0': 230, '1': 'logged in' }
Response handler: 230 logged in
calling : _endStopwatch > PASS PASSWORD {}
password sent
calling : _checkProc > PASS PASSWORD {}
check process for end:  ExeQueue {
  command: 'PASS PASSWORD',
  method: 'PASS',
  pipeData: [],
  pipeDataSize: 0,
  holdQueue: false,
  callback: [Function],
  runLevel: false,
  ended: 1492574330151,
  ping: 71,
  end: [Function],
  endStopwatch: [Function],
  checkProc: [Function],
  closeTransfer: [Function],
  closePipe: [Function],
  responseHandler: [Function],
  receiveData: [Function],
  started: 1492574330080 }
ExeQueue> Ending process: PASS PASSWORD
Event> endproc
Queue> Loading queue
--queue empty--
current dir: in
Queue.builder:: LIST . > setting 
undefined undefined
Queue> Registering callback...
Queue> processing: false; size: 0
Queue> Loading queue
Queue> Loaded...running
type set
holdQ:  true
ftp.Run:  true PASV
Queue> Registering callback...
Queue> processing: true; size: 0
Run> running callbackConstruct PASV
PASV 1 true
Run> command sent: PASV
....................

>>>
501 syntax error
>>>

501
------------------
CODE  -> 501
DATA -> syntax error
------------------
handle.data.waiting: true 501
handle.data.waiting:: 501 syntax error
calling : _responseHandler > PASV { '0': 501, '1': 'syntax error' }
Response handler: 501 syntax error
calling : _endStopwatch > PASV {}
handling error response code...
ExeQueue {
  command: 'PASV',
  method: 'PASV',
  pipeData: [],
  pipeDataSize: 0,
  holdQueue: true,
  callback: [Function: dataHandler],
  runLevel: 1,
  ended: 1492574330177,
  ping: 18,
  end: [Function],
  endStopwatch: [Function],
  checkProc: [Function],
  closeTransfer: [Function],
  closePipe: [Function],
  responseHandler: [Function],
  receiveData: [Function],
  started: 1492574330159 }
killing pipe
data not bound:  TypeError: Cannot read property 'removeListener' of null
    at ExeQueue._responseHandler (/mnt/app/sms/node_modules/ftpimp/index.js:408:21)
    at FTP.that.(anonymous function) (/mnt/app/sms/node_modules/ftpimp/index.js:308:32)
    at Object.onceWrapper (events.js:291:19)
    at emitTwo (events.js:106:13)
    at FTP.emit (events.js:192:7)
    at end (/mnt/app/sms/node_modules/ftpimp/index.js:824:25)
    at run (/mnt/app/sms/node_modules/ftpimp/index.js:847:17)
    at Socket.handle.data (/mnt/app/sms/node_modules/ftpimp/index.js:874:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:189:7)
error opening data port with PASV
Error: syntax error
    at ExeQueue._responseHandler (/mnt/app/sms/node_modules/ftpimp/index.js:415:27)
    at FTP.that.(anonymous function) (/mnt/app/sms/node_modules/ftpimp/index.js:308:32)
    at Object.onceWrapper (events.js:291:19)
    at emitTwo (events.js:106:13)
    at FTP.emit (events.js:192:7)
    at end (/mnt/app/sms/node_modules/ftpimp/index.js:824:25)
    at run (/mnt/app/sms/node_modules/ftpimp/index.js:847:17)
    at Socket.handle.data (/mnt/app/sms/node_modules/ftpimp/index.js:874:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:189:7)
calling : _checkProc > PASV {}
check process for end:  ExeQueue {
  command: 'PASV',
  method: 'PASV',
  pipeData: [],
  pipeDataSize: 0,
  holdQueue: true,
  callback: [Function: dataHandler],
  runLevel: 1,
  ended: 1492574330177,
  ping: 18,
  end: [Function],
  endStopwatch: [Function],
  checkProc: [Function],
  closeTransfer: [Function],
  closePipe: [Function],
  responseHandler: [Function],
  receiveData: [Function],
  started: 1492574330159 }
ExeQueue> Ending process, holding queue: PASV
current dir: 
....................

>>>
503 need USER first
>>>

503
------------------
CODE  -> 503
DATA -> need USER first
------------------
handle.data.waiting: false 503
....................

>>>
501 syntax error
227 Entering Passive Mode (***,***,***,***,145,63)
>>>

501, 227
------------------
CODE  -> 501
DATA -> syntax error
------------------
handle.data.waiting: false 501
------------------
CODE  -> 227
DATA -> Entering Passive Mode (***,***,***,***,145,63)
------------------
>executing command: startPassive
passive settings updated
handle.data.waiting: true 227
handle.data.waiting:: 227 Entering Passive Mode (***,***,***,***,145,63)
```
I had tried with `node-ftp` package and it did not work either. I am currently using `CentOS` and it works properly with the `ftp` command. I don't know if there is something wrong with my FTP server (I do not have the permission to see the configuration).

**Comment by sparkida** [comment]
I'm looking into this for you :)

**Comment by sparkida** [comment]
I've identified some issues running tests against various FTP services in CentOS, currently I test against PureFTPD and I have a ticket (https://github.com/sparkida/ftpimp/issues/27) for expanding portability that I will spend time on this weekend. I'm still not certain if that will fix things on your end, but hopefully...
